### PR TITLE
WIP: Codefresh

### PR DESCRIPTION
**Pull request by allanchau**
This PR enables deployment via Codefresh.

## Related PRs

- https://github.com/idearium/greenkeeper-lockfile/pull/1/files

### CODE REVIEW

**Comment by allanchau** [comment]
@smebberson This PR is ready for a quick review, but I'm not sure how to properly test it?

**Comment by smebberson** [comment]
@allanchau, do you mean test as in unit tests?

**Comment by allanchau** [comment]
@smebberson As in testing if a tagged commit will properly deploy it to production and if greenkeeper will update the lockfile when a package becomes out of date. I think we just have to wait until eslint or the comments plugin is updated to test greenkeeper?

**Comment by allanchau** [comment]
@smebberson If you haven't added the NPM token to the repo on codefresh I could also test it by doing an `alpha` tagged commit? As long as that fails at the deploy stage with some npm auth error we can assume it worked?

**Pull request closed without merging**
