### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by allanchau**
This is essentially the initial commit. Please review all files.

### Setup

- [ ] Clone the repo and link it to a project using the [instructions](http://eslint.org/docs/developer-guide/shareable-configs#publishing-a-shareable-config) listed here.
- [ ] Create an `.eslintrc` file with the contents:
```json
{
    "extends": "eslint-config-idearium"
}
```

### Testing

- [ ] Try it on a few of your projects and note any errors/warnings which you think are not quite right and do not follow our style guide.

### Notes

- Still waiting on an ESLint upgrade to the padding within blocks rule to allow no padding when there is only 1 line.
- `linter-eslint` in atom seems to be a few versions behind (doesn't support AST selectors) so you will have to install a local copy of eslint when testing.

### CODE REVIEW

**Comment by allanchau** [comment]
@idearium/developers Finally ready for testing when you get a chance!

**Comment by smebberson** [comment]
@allanchau, could we update it be under the `@idearium/eslint-config` namespace rather than `esling-config-idearium`?

**Comment by allanchau** [comment]
@smebberson No sure why, but eslint say:
> Make sure the module name begins with `eslint-config-`, such as `eslint-config-myconfig`.

http://eslint.org/docs/developer-guide/shareable-configs
I think it may be used when you do `"extends": "eslint-config-idearium"` or `"extends": "idearium"`

**Comment by smebberson** [comment]
@allanchau, ah, okay. Do you know if we could use the `@idearium` namespace?

**Comment by allanchau** [comment]
@smebberson ah it worked! I just had to update the paths in `browser.js` and `node.js`.

**Comment by allanchau** [comment]
BTW the linter-eslint in atom seems to be a few versions behind (doesn't support AST selectors) so you will have to install a local copy of eslint when testing. I'll add this to the notes in the description.

**Comment by allanchau** [comment]
@idearium/developers I'm going to merge this in so we can start referencing the git repo rather than individual commits.

**Pull request merged**
