### PR TITLE
Function paren newline

### PR DESCRIPTION
**Pull request by allanchau**
This PR Adds compatibility for v4.6.0 of eslint.

### CODE REVIEW

**Comment by allanchau** [comment]
@smebberson This pr is from Gitlab, moving it back here. Some of it is already live but I have also removed `consistent-return` that was breaking when using promises.
When you are happy with it, I will publish a new version (major?)

**Review by smebberson — APPROVED** [review]
Looks good!

**Comment by smebberson** [comment]
@allanchau, should I merge, or did you want to do some bump commits?

**Comment by allanchau** [comment]
@smebberson I'll do a release commit then merge it in.

**Pull request merged**
